# -*- coding: utf-8 -*-
"""p1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14j1z4EiqG_8CSrBdi5mIMqYB-95IXrM7
"""

"""
Problem 1: DFS & BFS

주어진 그래프 A를 0번 노드에서 시작하여
BFS와 DFS 방식으로 탐색하는 프로그램이다.

BFS는 시작 노드에서 가까운 노드부터 차례대로 탐색하고,
DFS는 한 방향으로 최대한 깊게 들어가며 탐색한다.

문제 조건에 따라 같은 단계 또는 같은 선택 상황에서
방문 가능한 노드가 여러 개 있을 경우,
번호가 작은 노드부터 방문하도록 구현하였다.
"""

from collections import deque


A = {
    0: [1, 2, 3],
    1: [0, 2, 4, 5],
    2: [0, 1, 6],
    3: [0],
    4: [1],
    5: [1],
    6: [2]
}


def bfs(A):
    """
    0번 노드에서 시작하여 BFS 방식으로 그래프를 탐색한다.

    BFS는 시작 노드와 가까운 노드부터
    차례대로 방문하는 탐색 방법이다. 이 함수에서는 큐를
    사용하여 먼저 발견한 노드를 먼저 방문하도록 설계하였다.

    같은 레벨에서 방문 가능한 노드가 여러 개 있을 경우,
    번호가 작은 노드부터 방문해야 하므로 인접 노드 목록을
    오름차순으로 정렬하여 확인한다.

    Parameters
    ----------
    A : dict
        각 노드와 그 노드에 연결된 인접 노드 목록을 저장한 그래프이다.

    Returns
    -------
    list
        BFS 방식으로 방문한 노드 번호를 순서대로 저장한 리스트이다.
    """
    answer = []

    # 이미 방문했거나 방문 예정인 노드를 저장하는 집합이다.
    # 같은 노드가 큐에 중복으로 들어가는 것을 막기 위해 사용한다.
    visited = set([0])

    # BFS는 먼저 들어온 노드를 먼저 처리해야 하므로 큐를 사용한다.
    queue = deque([0])

    while queue:
        # 큐의 가장 앞 노드를 꺼내 현재 방문 노드로 사용한다.
        node = queue.popleft()
        answer.append(node)

        # 번호가 작은 노드부터 방문하기 위해 오름차순 정렬한다.
        for next_node in sorted(A[node]):
            if next_node not in visited:
                visited.add(next_node)
                queue.append(next_node)

    return answer


def dfs(A):
    """
    0번 노드에서 시작하여 DFS 방식으로 그래프를 탐색한다.

    DFS는 한 방향으로 최대한 깊게 탐색한 뒤,
    더 이상 방문할 노드가 없으면 이전 노드로 돌아와 다른 경로를
    탐색하는 방법이다. 이 함수에서는 스택을 사용하여 구현하였다.

    스택은 나중에 넣은 값이 먼저 나오는 구조이므로,
    번호가 작은 노드가 먼저 방문되게 하려면 인접 노드를
    내림차순으로 스택에 넣어야 한다.

    또한 문제의 예시 결과인 [0, 1, 4, 5, 2, 6, 3]을 맞추기 위해
    노드를 스택에 넣는 순간 visited에 기록하여 중복 삽입을 방지한다.

    Parameters
    ----------
    A : dict
        각 노드와 그 노드에 연결된 인접 노드 목록을 저장한 그래프이다.

    Returns
    -------
    list
        DFS 방식으로 방문한 노드 번호를 순서대로 저장한 리스트이다.
    """
    answer = []

    # 시작 노드 0번은 처음부터 방문 예정으로 표시한다.
    visited = set([0])

    # DFS는 마지막에 넣은 노드를 먼저 처리해야 하므로 스택을 사용한다.
    stack = [0]

    while stack:
        # 스택의 가장 마지막 노드를 꺼내 현재 방문 노드로 사용한다.
        node = stack.pop()
        answer.append(node)

        # 스택은 나중에 넣은 노드가 먼저 나오므로,
        # 실제 방문 순서를 작은 번호부터 만들기 위해 내림차순으로 넣는다.
        for next_node in sorted(A[node], reverse=True):
            if next_node not in visited:
                visited.add(next_node)
                stack.append(next_node)

    return answer


bfs_result = bfs(A)
dfs_result = dfs(A)

assert bfs_result == [0, 1, 2, 3, 4, 5, 6]
assert dfs_result == [0, 1, 4, 5, 2, 6, 3]
print('PASSED!')