# -*- coding: utf-8 -*-
"""p2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10bd83TdqYZHKzn-IUs_oczAnUi-RaEhi
"""

import sys
from collections import deque

sys.stdin = open('case.txt')
N, M = list(map(int, input().split()))
# print(N, M)

concerts = []
for v in range(N):
    values = list(map(int, input().split()))
    concerts.append(values)

# print(concerts)
###################################


def count_stages(concerts):
    """
    콘서트장 약도에서 독립적인 무대 공간의 개수를 계산한다.

    문제 조건에서 콘서트장 약도는 0과 1로만 표시된다.
    1은 펜스가 있는 공간이고, 0은 빈 공간이므로 무대 공간이 될 수 있다.

    무대 공간은 상, 하, 좌, 우 방향으로 연결된 0들의 묶음이다.
    따라서 아직 방문하지 않은 0을 발견하면 새로운 무대 공간을 찾은 것이므로
    answer를 1 증가시키고, BFS를 이용해 그 공간과 연결된 모든 0을 방문 처리한다.

    콘서트장이 모두 1로 이루어진 경우에는 빈 공간이 없으므로
    무대 공간의 개수는 0이 된다.

    콘서트장이 모두 0으로 이루어진 경우에는 전체가 하나의 연결된
    무대 공간이므로 무대 공간의 개수는 1이 된다.

    Parameters
    ----------
    concerts : list
        0과 1로 이루어진 N x M 크기의 2차원 리스트이다.
        0은 무대 공간, 1은 펜스를 의미한다.

    Returns
    -------
    int
        서로 독립적으로 존재하는 무대 공간의 개수이다.
    """
    answer = 0

    # N과 M은 서로 다를 수 있으므로
    # 행의 개수와 열의 개수를 각각 따로 구한다.
    n = len(concerts)
    m = len(concerts[0])

    # 각 위치를 방문했는지 저장하는 2차원 리스트이다.
    # 이미 같은 무대 공간으로 처리한 0을 다시 세지 않기 위해 사용한다.
    visited = [[False] * m for _ in range(n)]

    # 상, 하, 좌, 우 네 방향만 연결된 공간으로 본다.
    # 대각선으로 붙어 있는 0은 같은 무대 공간으로 보지 않는다.
    dr = [-1, 1, 0, 0]
    dc = [0, 0, -1, 1]

    # 콘서트장 전체를 왼쪽 위부터 오른쪽 아래까지 확인한다.
    for r in range(n):
        for c in range(m):

            # 현재 칸이 0이고 아직 방문하지 않았다면
            # 새로운 독립 무대 공간을 발견한 것이다.
            if concerts[r][c] == 0 and not visited[r][c]:
                answer += 1

                # BFS 탐색을 시작하기 위해 큐에 현재 위치를 넣는다.
                queue = deque()
                queue.append((r, c))
                visited[r][c] = True

                # 현재 무대 공간과 연결된 모든 0을 찾아 방문 처리한다.
                while queue:
                    row, col = queue.popleft()

                    for i in range(4):
                        nr = row + dr[i]
                        nc = col + dc[i]

                        # 이동할 위치가 콘서트장 범위 안에 있는지 확인한다.
                        if 0 <= nr < n and 0 <= nc < m:

                            # 이동한 위치가 무대 공간인 0이고 아직 방문하지 않았다면
                            # 같은 무대 공간에 포함되므로 방문 처리 후 큐에 넣는다.
                            if concerts[nr][nc] == 0 and not visited[nr][nc]:
                                visited[nr][nc] = True
                                queue.append((nr, nc))

    return answer


print(count_stages(concerts))